server:
  port: 8080
spring:
  application:
    name: MoonhotelsHUB
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
